- src: https://github.com/mymesos/ansible-docker
  path: roles
  version: master
  scm: git

- src: https://github.com/AnsibleShipyard/ansible-java
  path: roles
  version: master
  scm: git

- src: https://github.com/mymesos/ansible-zookeeper
  path: roles
  version: master
  scm: git

- src: https://github.com/mymesos/ansible-mesos
  path: roles
  version: master
  scm: git

- src: https://github.com/mymesos/ansible-marathon
  path: roles
  version: master
  scm: git
