---
- hosts: slaves
  sudo: yes
  roles:
    - role: ansible-docker
      tags:
        - docker
    - role: ansible-mesos
      mesos_install_mode: slave
      tags:
        - mesos
        - mesos-slave